spring:
  security:
    user:
      name: ${AUTH_USERNAME}
      password: ${AUTH_BCRYPT_ENCODED_PASSWORD}
  application:
    name: inventory
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

server:
  servlet:
    context-path: /api
