spring:
  security:
    user:
      name: user
      password: $2a$12$tHPJUAUq48pVQJi1VFOKvu7EfJUOB8n/wYOBGM64Kehh/V3XsmyYW
  application:
    name: inventory
  datasource:
    username: user
    password: password
    url: jdbc:mariadb://localhost:3306/db
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    context-path: /api
